theme                  : "jekyll-statuspage"

title: "Jekyll Statuspage"
baseurl: "" # only need if your site is hosted as a subdomain, e.g. on GH Pages
url: "" # url of your site

plugins:
  - jekyll-remote-theme

#
# Statuspage-specific Options
#

brand:
    title: Jekyll Statuspage
    logo:
    logo-text: "Jekyll Statuspage"

color-scheme: # blue, dark or red (light is default)
fa-code: # code for font awesome